### ISSUE TITLE
Coarse dirt render

### ISSUE THREAD

**Issue by roman901** [NeoRaider/MinedMap#1]
Hello!

I've rendered some of my worlds and see, that coarse dirt drawed incorrectly.
![screenshot from 2018-11-07 11-47-24](https://user-images.githubusercontent.com/2963008/48120475-4326a780-e283-11e8-8876-350c243560e5.png)
![2018-11-07_11 47 19](https://user-images.githubusercontent.com/2963008/48120491-4fab0000-e283-11e8-8348-18779652f79f.png)

**Comment by roman901** [comment]
UPD: maybe not curse dirt, but glitchy fragment always contains it...

![2018-11-07_11 52 42](https://user-images.githubusercontent.com/2963008/48120613-aa445c00-e283-11e8-8a63-98bfcbfb6ff4.png)
![screenshot from 2018-11-07 11-52-47](https://user-images.githubusercontent.com/2963008/48120621-b0d2d380-e283-11e8-9f1c-34a3910ab1d2.png)

**Comment by NeoRaider** [comment]
Hmm, the problem does not seem to be connected with a specific block type, but rather the biome modifier that all colors of grass and foliage are multiplied with. Looking at MinedMap's current list of biome definitions, the badlands colors are way off... (And I also missed to add a number of new MC 1.13 biome types)

I going to fix this up soon.

**Comment by NeoRaider** [comment]
I've fixed the issue in the latest git master. As the new color computation changes a lot of other colors as well, I'll have to make a few more tests to decide if I'm happy with the overall look.

I plan to make a new binary release with the fix next week.
