### ISSUE TITLE
index.html not appearing

### ISSUE THREAD

**Issue by OfficialPixelBrush** [NeoRaider/MinedMap#14]
Dunno why. No errors, but there's no index.html anywhere.

**Comment by NeoRaider** [comment]
Most content of the "viewer" directory is static, it contains `index.html`, `MinedMap.js` and the Leaflet library, as found in the Git repo or the released viewer ZIP. The actual MinedMap generator only creates the data files (map tiles + JSON metadata) to be used by the viewer.

So you would unpack the viewer somewhere where your webserver finds it, and then run MinedMap as
```
</path/to/MinedMap> </path/to/my/minecraft/savegame> </path/to/the/viewer>/data
```
(that is, the final `/data` must be part of the passed path, so the data is generated in the `data` subdir of the viewer directory.
