### ISSUE TITLE
Odd issue, viewer does not seem to update

### ISSUE THREAD

**Issue by DerekCresswell** [NeoRaider/MinedMap#15]
I'm sure this is just something simple I am missing but I've been staring at it and have to come here.

I've got a server that I would like to render every once and a while. So have I have 2 renders and the map has changed significantly but when put in the viewer no changes are visible.

I am inputting the `data/world` folder of my server (which is the one that contains data, region, playerdata, etc. pretty sure this is the folder I want). I'm outputting it to some folders just named with the dates taken. Manually inspecting the map folder I can see that the generated pngs have the correctly updated map.

However, when I move the data folder into the `viewer/` directory and turn on a python server I cannot see the changes; it still displays the old map despite that folder no longer being present.

So, what I am missing with the viewer? Thanks a bunch.

**Comment by NeoRaider** [comment]
- Have you ruled out a browser cache issue? In most browsers you can reload the page bypassing cache using a key combination like Ctrl+F5. You can also try a different browser. When putting the files on a real web server, adding an HTTP header with short cache expire time may be advisable.
- Please double check that the files are in the right place. The "data" directory should be in the same directory where "index.html" and "MinedMap.js" are located, with "data" having a file "info.json" and subdirectories "map", "light" and "biome".

**Comment by DerekCresswell** [comment]
I had checked and saw no caching issues, I did have it in the right directories. Just turned it on again and it worked so I guess it was some mystery cache issue. Sorry for bothering you!
Thanks for the project, I'd be happy to help if you have future plans or issues to work out.
