### ISSUE TITLE
1.17 Compatibility

### ISSUE THREAD

**Issue by saadbruno** [NeoRaider/MinedMap#16]
It's been a few weeks since 1.17 came out with lots of new blocks! I'm just creating this issue so we can track progress for implementing these into MinedMap.

I have some basic programming knowledge, I'm happy to help with implementation if needed!

**Comment by NeoRaider** [comment]
Thanks for the reminder! I really need to document how to generate the resource data, so it's easier for other to contribute to the project.

Minecraft 1.17 really added a lot of new stuff - a quick diff counts 137 new block types (and one removed type "grass_path", which I'll have to check and decide how to deal with - I assume it was just renamed and corresponds to the new type "dirt_path").

**Comment by saadbruno** [comment]
> and one removed type "grass_path", I assume it was just renamed and corresponds to the new type "dirt_path"

That is correct. I'm guessing they renamed it cause now you don't need grass to create the paths. You can right click dirt with a shovel and it also works. But it's the same block per say.

Here's a screenshot of how villages render currently. It shows the default brown, which is the same for the new blocks.
![image](https://user-images.githubusercontent.com/23201434/122991650-a6ee3800-d37b-11eb-882f-ad7dc5c2cb5f.png)



As to how to deal with it, i think we keep "grass_path" for backwards compatibility, and just add "dirt_path" with the same color.

**Comment by DerekCresswell** [comment]
Just here to +1 and say I'd be happy to help out when issues arise!

**Comment by NeoRaider** [comment]
Untested support added in #17. I should be able to finish this on the weekend.
