### ISSUE TITLE
1.19 support

### ISSUE THREAD

**Issue by dreadnaut** [NeoRaider/MinedMap#27]
Hello there!
Would you be able to upgrade MinedMap to handle the mud and deep dark blocks that come with 1.19? 🙇

**Comment by NeoRaider** [comment]
Sorry about the delay! The 1.19 support had been stewing in the `main` branch for a few months, but I had completely forgotten to make a proper release.

**Comment by dreadnaut** [comment]
Thank you again!

**Comment by dreadnaut** [comment]
New blocks seem to work fine, although I am still seeing several of these lines in the logs:
```
Warning: unknown biome: minecraft:deep_dark
```

**Comment by NeoRaider** [comment]
Huh, seems like we missed one of the new block types.

**Comment by NeoRaider** [comment]
Ah, it's a new biome, and the new block types were added.

**Comment by NeoRaider** [comment]
Pushed a new branch `biomes-1.19` that adds the new biomes. Completely untested for now, will need to check if my test savegames contain both new biomes.

**Comment by dreadnaut** [comment]
I gave it a try on the same world as above, and no errors this time 👍
