### ISSUE TITLE
1.16 compatibility

### ISSUE THREAD

**Issue by dreadnaut** [NeoRaider/MinedMap#6]
Minecraft 1.16 is upon us, and it comes with several new blocks.

I'm not sure which information is needed, but I'd be happy to help digging it out, to get MinedMap compatible as soon as possible.

**Comment by NeoRaider** [comment]
Wow, that's a lot of new block types... Thanks for the reminder, I should be able to take care of it on the weekend.

A quick diff on `assets/minecraft/blockstates` in the Minecraft .jar gives me 83 new block IDs:
```
ancient_debris
basalt
blackstone
blackstone_slab
blackstone_stairs
blackstone_wall
chain
chiseled_nether_bricks
chiseled_polished_blackstone
cracked_nether_bricks
cracked_polished_blackstone_bricks
crimson_button
crimson_door
crimson_fence
crimson_fence_gate
crimson_fungus
crimson_hyphae
crimson_nylium
crimson_planks
crimson_pressure_plate
crimson_roots
crimson_sign
crimson_slab
crimson_stairs
crimson_stem
crimson_trapdoor
crimson_wall_sign
crying_obsidian
gilded_blackstone
lodestone
netherite_block
nether_gold_ore
nether_sprouts
polished_basalt
polished_blackstone
polished_blackstone_bricks
polished_blackstone_brick_slab
polished_blackstone_brick_stairs
polished_blackstone_brick_wall
polished_blackstone_button
polished_blackstone_pressure_plate
polished_blackstone_slab
polished_blackstone_stairs
polished_blackstone_wall
potted_crimson_fungus
potted_crimson_roots
potted_warped_fungus
potted_warped_roots
quartz_bricks
respawn_anchor
shroomlight
soul_campfire
soul_fire
soul_lantern
soul_soil
soul_torch
soul_wall_torch
stripped_crimson_hyphae
stripped_crimson_stem
stripped_warped_hyphae
stripped_warped_stem
target
twisting_vines
twisting_vines_plant
warped_button
warped_door
warped_fence
warped_fence_gate
warped_fungus
warped_hyphae
warped_nylium
warped_planks
warped_pressure_plate
warped_roots
warped_sign
warped_slab
warped_stairs
warped_stem
warped_trapdoor
warped_wall_sign
warped_wart_block
weeping_vines
weeping_vines_plant
```

**Comment by dreadnaut** [comment]
Great, thank you!

**Comment by NeoRaider** [comment]
I have just pushed a large update that adds 1.16 block support, as well as many other improvements (fixed spruce and birch leaf colors, fixed default and swamp water colors, warm/lukewarm ocean colors, as well as smooth transitions between biomes, similar to the way Minecraft renders this.)

Full release notes will follow soon.

**Comment by dreadnaut** [comment]
Smooth transitions look great! And so do the ocean colors. The swamp water is very green, maybe it could lean more toward a blue-green tint?

I haven't tried rendering a 1.16 world yet, but I'll do it in the next days. Thanks for the update!

**Comment by NeoRaider** [comment]
Swamp water color is chosen according to: https://minecraft.gamepedia.com/Water#Java_Edition

**Comment by dreadnaut** [comment]
It is the correct color, yes, but it's still a bit confusing on a map, since it's very close to some kinds of terrain. I suppose I can always change it before I compile MinedMap 🙂

**Comment by dreadnaut** [comment]
I have not tried *all* the new blocks, but rendering seems to work fine with 1.16 worlds. Thank you!
