### ISSUE TITLE
image-rendering: crisp-edges not works

### ISSUE THREAD

**Issue by roman901** [NeoRaider/MinedMap#7]
In chromium-based browsers (and Safari as webkit-based) map with max scale looks so blurry.
![Снимок экрана 2020-06-28 в 02 43 42](https://user-images.githubusercontent.com/2963008/85934297-bca45b00-b8e9-11ea-87d7-9bf40b425e12.png)

In Firefox - all ok
![Снимок экрана 2020-06-28 в 02 43 59](https://user-images.githubusercontent.com/2963008/85934302-c29a3c00-b8e9-11ea-9a4d-0ccc5a176f0f.png)

I do some research but can't realize why is broken. A leaflet bugtracker contains old notices about this bug, but nothing about a solution.

**Comment by roman901** [comment]
![Снимок экрана 2020-06-28 в 17 00 45](https://user-images.githubusercontent.com/2963008/85949685-eba9e380-b960-11ea-8edf-7fb6855d1313.png)
Problem is still there

**Comment by NeoRaider** [comment]
Hmm, I can't reproduce this with Chromium 83 anymore.

**Comment by roman901** [comment]
Checked again: in chrome all ok, in safari rendering is still blurry. Looks like Safari don't support any of image-rendering modes in this case.
